---
version: "3.8"

services:
  # Test Vector Database (Qdrant)
  qdrant-test:
    image: qdrant/qdrant:v1.14.1@sha256:a9dc5625b10e4d3a3b53e3e6686f23e7302f73c0c07e157fc4d1cff6abf607ba
    ports:
      - "6333:6333"
      - "6334:6334" # gRPC port
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - test-network
    tmpfs:
      - /qdrant/storage # Use tmpfs for faster test execution

  # Test Graph Database (Neo4j)
  neo4j-test:
    image: neo4j:5.15-community@sha256:49209c959ae23185b7625d0f9185b59cb82269f2dfbeba266376afd1f55d4ed9
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=256m
    healthcheck:
      test:
        ["CMD", "sh", "-c", "cypher-shell -u neo4j -p testpassword 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - test-network
    tmpfs:
      - /data # Use tmpfs for faster test execution
      - /logs

  # Test Cache/KV Store (Redis)
  redis-test:
    image: redis:7-alpine@sha256:9296d9dd2004d0b9c502ceefb67c8c3c0ac6d619e8ace6b3877bc755468bc786
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - test-network
    tmpfs:
      - /data # Use tmpfs for faster test execution

networks:
  test-network:
    driver: bridge
