app = "veris-memory"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.flyio"

[env]
  MCP_SERVER_PORT = "8000"
  LOG_LEVEL = "info"
  QDRANT_URL = "http://localhost:6333"
  NEO4J_URI = "bolt://localhost:7687"
  NEO4J_USER = "neo4j"
  REDIS_URL = "redis://localhost:6379"
  # NEO4J_PASSWORD must be set as a Fly.io secret: flyctl secrets set NEO4J_PASSWORD=your_secure_password

# Volume for persistent storage - databases + logs
[[mounts]]
  source = "veris_memory_data"
  destination = "/app/data"
  processes = ["app"]

# Services configuration
[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    port = 8000

  [[services.http_checks]]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"

# Resource allocation - Meeting Fly.io 8GB minimum requirement
[[vm]]
  memory = "8gb"
  cpu_kind = "performance"
  cpus = 4

# Process groups for multi-service deployment
[processes]
  app = "/app/start-services.sh"

# Deploy configuration
[deploy]
  strategy = "immediate"

# DNS configuration
[[dns]]
  nameservers = ["1.1.1.1", "8.8.8.8"]

# Network configuration for static IPs
[network]
  ipv4 = "dedicated"  # This will allocate a dedicated IPv4 address
  ipv6 = true         # This enables IPv6 with static allocation
